### ISSUE TITLE
Code content don't show in Golive preview

### ISSUE THREAD

**Issue by AliyahHA** [AliyahHA/to-do-app#1]
### There is an error in the code.

- when previewing the Golive in VS code the code content do not appear & rather I can only see the files in the project folder.

- Screenshots are attached below:

![Screen Shot 2024-03-01 at 6 28 50 PM](https://github.com/AliyahHA/to-do-app/assets/53529035/190c2454-f4e9-4a0c-b9e0-f24e794e5066)

![1](https://github.com/AliyahHA/to-do-app/assets/53529035/0f69f6fa-1efc-4e53-949d-6f28cb3da07d)
![2](https://github.com/AliyahHA/to-do-app/assets/53529035/255c925b-c90b-4973-8cfb-86bb01a16f9c)

@Beamanator

**Comment by ahmed-hamid-dev** [comment]
Try it with `npm start`. It will open the app in dev mode on port 3000

**Comment by AliyahHA** [comment]
[Issue resolved ](https://github.com/AliyahHA/to-do-app/commit/b32b28feef505441b36497c3556b065696b17d98)
